UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(id_product_type) FROM product_type),100) WHERE SEQ_NAME='product_type';
UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(id_file) FROM file),0) WHERE SEQ_NAME='file';
UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(id_maker) FROM maker),100) WHERE SEQ_NAME='maker';
UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(id_maker) FROM maker),100) WHERE SEQ_NAME='product_type';
UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(id_maker) FROM maker),100) WHERE SEQ_NAME='maker';
UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(id_maker) FROM maker),100) WHERE SEQ_NAME='maker';