UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(ID_PRODUCT_TYPE) FROM product_type),100) WHERE SEQ_NAME='product_type';
UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(ID_FILE) FROM FILE),0) WHERE SEQ_NAME='file';
UPDATE SEQUENCE SET SEQ_COUNT=COALESCE((SELECT MAX(ID_SELLER) FROM SELLER),100) WHERE SEQ_NAME='seller';